"""initial schema

Revision ID: 0b11f06365cd
Revises:
Create Date: 2026-09-06 23:16:20.305951

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b11f06365cd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "function",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_function_key"), "function", ["key"], unique=True)
    op.create_table(
        "lc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "LC", "MC", name="lctype", native_enum=False, length=10, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lc_name"), "lc", ["name"], unique=True)
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("preferred_name", sa.String(), nullable=True),
        sa.Column("aiesec_email", sa.String(), nullable=False),
        sa.Column("personal_email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("join_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ALUMNUS",
                "INACTIVE",
                "ANONYMISED",
                name="personstatus",
                native_enum=False,
                length=20,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("anonymised_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_person_aiesec_email"), "person", ["aiesec_email"], unique=True)
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_key"), "position", ["key"], unique=True)
    op.create_table(
        "term",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "membership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("lc_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["function.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lc_id"],
            ["lc.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lc_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("term_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("leader_membership_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["function.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lc_id"],
            ["lc.id"],
        ),
        sa.ForeignKeyConstraint(
            ["leader_membership_id"],
            ["membership.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["term.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["membership.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_member")
    op.drop_table("team")
    op.drop_table("membership")
    op.drop_table("term")
    op.drop_index(op.f("ix_position_key"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_person_aiesec_email"), table_name="person")
    op.drop_table("person")
    op.drop_index(op.f("ix_lc_name"), table_name="lc")
    op.drop_table("lc")
    op.drop_index(op.f("ix_function_key"), table_name="function")
    op.drop_table("function")
    # ### end Alembic commands ###
