"""add audit_log

Revision ID: 4566b47c3298
Revises: 0b11f06365cd
Create Date: 2026-09-25 21:24:31.801938

Creates `audit_log` (spec §8.4) and makes it append-only **at the database
level** with triggers that reject UPDATE, DELETE and TRUNCATE for every role,
the table owner included. The triggers are hand-written: autogenerate doesn't
detect triggers, so a future autogenerated migration won't touch them either.
Why a trigger rather than GRANTs: `docs/data-model.md` → "audit_log".
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4566b47c3298"
down_revision: str | Sequence[str] | None = "0b11f06365cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("actor_membership_id", sa.Integer(), nullable=True),
        sa.Column("actor_person_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)

    # One function shared by both triggers: it only ever raises, so any
    # statement that fires it is rejected and its transaction rolled back.
    op.execute(
        """
        CREATE FUNCTION audit_log_block_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (spec §8.4): % is not allowed',
                TG_OP;
        END;
        $$;
        """
    )
    # Row-level: fires for each row an UPDATE or DELETE touches.
    op.execute(
        """
        CREATE TRIGGER audit_log_no_update_or_delete
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();
        """
    )
    # TRUNCATE doesn't fire row-level triggers, so it needs its own
    # statement-level one — otherwise it would empty the log silently.
    op.execute(
        """
        CREATE TRIGGER audit_log_no_truncate
        BEFORE TRUNCATE ON audit_log
        FOR EACH STATEMENT EXECUTE FUNCTION audit_log_block_mutation();
        """
    )
    # By default triggers don't fire when a session sets
    # `session_replication_role = replica` — a one-line bypass that needs no
    # schema change. `ENABLE ALWAYS` makes them fire in every mode.
    op.execute("ALTER TABLE audit_log ENABLE ALWAYS TRIGGER audit_log_no_update_or_delete;")
    op.execute("ALTER TABLE audit_log ENABLE ALWAYS TRIGGER audit_log_no_truncate;")


def downgrade() -> None:
    """Downgrade schema.

    WARNING: this deletes the whole audit log. Fine locally; never run it
    against production without a backup and Tech Lead sign-off.
    """
    # DROP TABLE removes the table's triggers with it; the function is separate.
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_table("audit_log")
    op.execute("DROP FUNCTION audit_log_block_mutation();")
